- id: check-msg-format-on-push
  name: simple-commit-message-format
  description: "Validates commit message format"
  entry: push-main.sh
  language: script
  always_run: true
  stages: [push]

- id: check-msg-format-on-commit
  name: simple-commit-message-format
  description: "Validates commit message format"
  entry: commit-main.sh
  language: script
  always_run: true
  stages: [commit-msg]
